version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend